# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"URLs.AUDIOMDPI": "00_core.ipynb",
         "URLs.MARCO": "00_core.ipynb",
         "URLs.SIGNALTRAIN_LA2A_1_1": "00_core.ipynb",
         "URLs.SIGNALTRAIN_LA2A_REDUCED": "00_core.ipynb",
         "zenodo_url_to_data_url": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://drscotthawley.github.io/fastproaudio/"

git_url = "https://github.com/drscotthawley/fastproaudio/tree/master/"

def custom_doc_links(name): return None
